In [34]:
import numpy as np
import time

# Performance: Numpy x Python

In [35]:
size = 1000000

In [36]:
# python
list_py = []
list_py = [x for x in range(size)]
print(list_py[:10])
print(list_py[-10:])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[999990, 999991, 999992, 999993, 999994, 999995, 999996, 999997, 999998, 999999]


In [41]:
start_time_py = time.process_time()
list_py_mult = [x*2 for x in list_py]
duration_py = time.process_time() - start_time_py
print(duration_py)

0.03125


In [38]:
print(list_py_mult[:10])
print(list_py_mult[-10:])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[1999980, 1999982, 1999984, 1999986, 1999988, 1999990, 1999992, 1999994, 1999996, 1999998]


In [39]:
# numpy
arr_np = np.array(arr_py)
print(arr_np[:10])
print(arr_np[-10:])

[0 1 2 3 4 5 6 7 8 9]
[999990 999991 999992 999993 999994 999995 999996 999997 999998 999999]


In [42]:
start_time_np = time.process_time()
arr_np_mult = arr_np*2
duration_np = time.process_time() - start_time_np
print(duration_np)

0.015625


In [44]:
# comparison
print(f'numpy array is {duration_np/duration_py*100}% faster than python list')

numpy array is 50.0% faster than python list


# Working with Numpy Arrays

## Creating Arrays and Matrices

In [137]:
# creating arrays
l = [1,2,3]
np_array = np.array(l)
np_array

array([1, 2, 3])

In [138]:
print(type(l))
print(type(np_array))

<class 'list'>
<class 'numpy.ndarray'>


In [139]:
# creating matrix with python
py_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(py_matrix, type(py_matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] <class 'list'>


In [140]:
# creating matrix with numpy
np_matrix = np.matrix(py_matrix)
print(np_matrix, type(np_matrix))
print('------------------------------')
# another option
np_matrix_ = np.array(py_matrix)
print(np_matrix_, type(np_matrix_))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.matrix'>
------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [54]:
# 1D array
np.array([1,2,3])

array([1, 2, 3])

In [56]:
# 2D array
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
# 3D array
np.array([[[1,2,3],[4,5,6],[7,8,9]],
         [[11,12,13],[14,15,16],[17,18,19]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [62]:
# some more options with python lists
list_range = list(range(10))
print(list_range)
print(type(list_range))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [63]:
# some more options with python lists
array_range = np.array(range(10))
print(array_range)
print(type(array_range))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [64]:
array_steped = np.arange(1, 101, 3)
print(array_steped, type(array_steped))

[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100] <class 'numpy.ndarray'>


In [66]:
# numpy array with zeros
zeros = np.zeros(5)
print(zeros, type(zeros))

[0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


In [69]:
# numpy matrix with zeros
zeros_matrix = np.zeros((3, 3))
print(zeros_matrix, type(zeros_matrix))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>


In [70]:
# numpy array with ones
ones = np.ones(5)
print(ones, type(ones))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [71]:
# numpy matrix with ones
ones_matrix = np.ones((3, 3))
print(ones_matrix, type(ones_matrix))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'>


In [74]:
# linspace(start, end, n) creates an array with lenght=n 
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [75]:
# creating an identity matrix (https://en.wikipedia.org/wiki/Identity_matrix)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
# creating a random matrix
np.random.rand(3,4)

array([[0.03229509, 0.72308595, 0.45817809, 0.54484875],
       [0.40926921, 0.12960762, 0.00879705, 0.81876546],
       [0.54809669, 0.11766774, 0.18054078, 0.45588789]])

In [83]:
# creating a random matrix (in this case we need to input a tuple)
np.random.random((3,4))

array([[0.07953198, 0.49963792, 0.15708943, 0.94503473],
       [0.52236453, 0.10293601, 0.86824684, 0.46088973],
       [0.4847258 , 0.04422707, 0.07492552, 0.82027852]])

In [87]:
# creating a random matrix using Gaussian distribution (https://en.wikipedia.org/wiki/Normal_distribution)
print(np.random.randn(10))
print('----------------------------')
print(np.random.randn(3,3))

[-0.34419239  0.32939488 -1.04923073  0.49191353 -1.47090853  0.07362426
 -0.46313192  0.91134424  0.06527936 -0.2672725 ]
----------------------------
[[-1.10213418 -0.21827088  0.04096494]
 [ 0.37222222  0.52981177  1.6049021 ]
 [ 0.00509762 -1.93387029  2.09236306]]


In [89]:
# creating a seed to random algorithm, this mean the following 'random values' will be the same ALWAYS
np.random.seed(3)

np.random.randint(25, size=(3,3))

array([[10, 24,  3],
       [24,  8,  0],
       [21, 19, 10]])

## Reshape

In [90]:
# reshaping arrays
normal = np.arange(15)
normal

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
# reshaping arrays
reshaped = normal.reshape(3, 5)
reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Max, ArgMax, Min, ArgMin

In [93]:
a = np.random.randint(25, size=(3,3))
a

array([[11,  9, 10],
       [21, 23,  6],
       [ 0, 20, 12]])

In [94]:
# max value
a.max()

23

In [96]:
# max value position
a.argmax()

4

In [95]:
# min value
a.min()

0

In [97]:
# min value position
a.argmin()

6

## Sorting Arrays

In [99]:
a = np.random.randint(25, size=(5,5))
a

array([[14, 20, 23, 22,  0],
       [ 0,  9, 18, 20,  5],
       [24, 24,  7,  5, 14],
       [ 1, 17,  1, 21, 21],
       [23, 10, 11,  4,  3]])

In [100]:
# sorting array
np.sort(a)

array([[ 0, 14, 20, 22, 23],
       [ 0,  5,  9, 18, 20],
       [ 5,  7, 14, 24, 24],
       [ 1,  1, 17, 21, 21],
       [ 3,  4, 10, 11, 23]])

In [103]:
# indexing
indexing = np.arange(0,21)
indexing

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [105]:
div_indexing = indexing[:11].copy()
div_indexing

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
div_indexing[:] = 999

In [107]:
div_indexing

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [108]:
indexing

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [109]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
array_2d[2, 2]

9

In [114]:
array_6d = np.random.randint(30, size=(6,6))
array_6d

array([[23,  3, 20, 17, 22, 28],
       [11,  7, 25,  1, 11,  0],
       [28, 28, 28, 16, 27, 21],
       [11,  8, 20,  8, 24, 14],
       [12, 19,  4,  9, 26, 18],
       [28,  5, 20, 23,  9, 10]])

In [116]:
# selecting some part of the array_6d
array_6d[3:,3:]

array([[ 8, 24, 14],
       [ 9, 26, 18],
       [23,  9, 10]])

In [118]:
array_6d[2,1:4]

array([28, 28, 16])

In [119]:
# boolean decisions
array_6d >= 5

array([[ True, False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [123]:
array_6d[array_6d>=5]

array([23, 20, 17, 22, 28, 11,  7, 25, 11, 28, 28, 28, 16, 27, 21, 11,  8,
       20,  8, 24, 14, 12, 19,  9, 26, 18, 28,  5, 20, 23,  9, 10])

In [124]:
np.unique(array_6d)

array([ 0,  1,  3,  4,  5,  7,  8,  9, 10, 11, 12, 14, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28])

In [125]:
# some calculations with arrays
mat = np.random.randint(0,15,5)
mat

array([ 1,  9,  0, 13, 14])

In [126]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [127]:
mat+ones

array([ 2., 10.,  1., 14., 15.])

In [128]:
ones = np.ones(5)*3
ones

array([3., 3., 3., 3., 3.])

In [129]:
mat*ones

array([ 3., 27.,  0., 39., 42.])

In [130]:
mat**ones

array([1.000e+00, 7.290e+02, 0.000e+00, 2.197e+03, 2.744e+03])

In [131]:
np.sin(mat)

array([0.84147098, 0.41211849, 0.        , 0.42016704, 0.99060736])

In [132]:
np.cos(mat)

array([ 0.54030231, -0.91113026,  1.        ,  0.90744678,  0.13673722])

In [133]:
np.tan(mat)

array([ 1.55740772, -0.45231566,  0.        ,  0.46302113,  7.24460662])